/*  MY NAME=JOHN F KENNEDY MY ID=JFK63
		
		CORRECT OUTPUT 5 PTS	 CORRECT EXPLANATION 2 POINTS
--------------------------------------------------------------------------
MYSTERY #1:  (1) <951413>	(2) <PRINTS INTEGER BACKWARDS>
MYSTERY #2:  (1) <23>	(2) <ADDS TOGETHER THE INTEGERS WITHIN AN INTEGER>
MYSTERY #3:  (1) <23>	(2) <ADDS TOGETHER THE INTEGERS IN AN ARRAY>
MYSTERY #4:  (1) <RETURNED FALSE>	(2) <CHECKS IF INTEGERS IN ARRAY ARE SORTED>
MYSTERY #5:  (1) <5 4 3 2 1 >	(2) <PRINTS ALL THE INTEGERS FROM THE INPUT TO 1>
MYSTERY #6:  (1) <1 2 3 4 5 >	(2) <PRINTS ALL THE INTEGERS FROM 1 TO THE INPUT>
MYSTERY #7:  (1) <5 4 3 2 1 1 2 3 4 5 >	(2) <PRINTS ALL THE INTEGERS FROM THE INPUT TO 1 AND THEN DOES IT IN REVERSE>
*/